### ISSUE TITLE
Image not using node tagged version

### ISSUE THREAD

**Issue by LucaPrete** [trion-development/docker-ng-cli#13]
Hello there!

First of all, thanks for the great images. They're super useful and it's great that someone is able to maintain them!

I'd like to point out that since version 7.x this image is no longer built from a tagged version of node.
This may cause some issues with modules that both require a specific version of ng-cli, and specific versions of node.

For example, I still use angular 6.0.7, which installs node-sass 4.9.0, which requires node 10 to work.

Unfortunately, the 6.0.7 image uses node 8 instead (which is not supported at all by node-sass 4.9.0).
Images from 7.x and above point to the latest version of node available, which makes things work, but require node-sass to be compiled at each run, with lots of time lost.

For my personal needs, having a 6.0.7 image with node 10.x would be perfect.

Any thought?

Thank you!

**Comment by everflux** [comment]
The current idea is to build and release a new docker image once a new angular cli version becomes available. It uses the node-lts base image that is current at that time. The assumption
Since there are many variables it would become quite hard to support a matrix-style build with the cross product of node and angular-cli versions. 
Updating old images to use a newer node version could lead to problems for users that rely on the stability of an image - consider the case that you used trion/ng-cli:6.0.7. a couple of months ago and everything works out great, but once the image gets repulled (f.e. a different build node) the build breaks since the tagged image changed. This is exactly the case to be avoided by using a docker image...

For your case: I would like to kindly suggest to update to Angular 8 (or 9) - I know that the migration is some effort, but it gets better with each Angular version. If it is just a resource or knowhow problem, we are happy to offer support/development ;)

Although I hesitate to suggest it, since updating your project would be the right way to go, another solution is to build a custom image. This might at least help your immediate . This is really quite easy: Clone the repo, change to the cloned directory and build the image:
```docker build --build-arg NG_CLI_VERSION=6.0.7 -t custom/ng-cli:6.0.7 .```
(Note the dot at the end!)

**Comment by LucaPrete** [comment]
Thanks @everflux !

Of course, I see your point. Upgrading immediately is unfortunately not an option.
The procedure to use create the custom image was clear. I just wanted to check first if something else could be done on the already existing image.

Thanks again!
