### ISSUE TITLE
Use same default user as the ng-cli-e2e and ng-cli-karma images

### ISSUE THREAD

**Issue by SebastianOltmanns** [trion-development/docker-ng-cli#21]
I want to use all three trion-ng-cli images (ng-cli, ng-cli-e2e, ng-cli-karma) for CI/CD, using Gitlab Runners. The pipeline basically looks like that: 
1. run karma tests using ng-cli-karma image
2. run e2e tests using ng-cli-e2e image
3. build and package using ng-cli image

In between those jobs, I want to cache npm dependencies. Sadly, the third job fails due to "operation permitted" when trying to change some of the npm cache. The reason here is that the ng-cli-e2e and ng-cli-karma images have `root` as default user, and the npm cache created by the first image is owned by the `root` user. Using the ng-cli image in the third job, the default user is `node`, not having write permissions for the npm cache created by the `root` user.

To illustrate my issue, I ran these commands:

```
PS C:\Users\Sebastian Oltmanns> docker run trion/ng-cli whoami
node
PS C:\Users\Sebastian Oltmanns> docker run trion/ng-cli-e2e whoami
root
PS C:\Users\Sebastian Oltmanns> docker run trion/ng-cli-karma whoami
root
```

I may be wrong in any conclusion. Maybe there is some other reason for this behaviour. Can somebody help me with this?

**Comment by everflux** [comment]
Thanks for pointing out this inconsistency. I will look into what might have driven the decision in regards to the different default users.

Since you described your use case I would like to add, that the images are designed to be a superset with added features. So you will get karma capability and the CLI in the karma image, the e2e image will add java for protractor. So you could easily just the use karma image and don‘t use the plain cli image at all. Or even just use the e2e image. If you are going to use all features anyway, it would save you some bandwidth and storage space to use just a single image.

**Comment by everflux** [comment]
I have pushed a fix to use unprivileged users in all images. Would be cool, if you could verify that it solves your issue. (DockerHub build is running, images will be tagged with :latest )

**Comment by everflux** [comment]
This change seems to break some builds. I will revert it for now.

**Comment by SebastianOltmanns** [comment]
@everflux any updates on this?

**Comment by everflux** [comment]
I am afraid there is one group or another for which the image works out of the box without further configuration. 
Since a change would break existing configurations I think we need to stick to the current user handling. 

For your use case I recommend that you explicitly configure the user to use for execution of the image. This should fix your issue. 
besides you may want to use just the e2e image instead different images for each stage. Or is there something I am missing?

**Comment by SebastianOltmanns** [comment]
Yes, using the e2e image fixes my issue, thank you for that hint. I just wanted to ask if you are planning on "fixing" that inconsistency out of curiosity :)

**Comment by everflux** [comment]
Since it would break backwards compatibility I think there is no smooth way to accomplish that. But I am open to ideas and suggestions :)
