### ISSUE TITLE
Unable to update or install with apt-get

### ISSUE THREAD

**Issue by cray2015** [trion-development/docker-ng-cli#8]
Hi There,

I was using your image file to use it in my bit bucket pipeline. however I need to install the zip package in the docker but I'm getting the permission errors as below:
```
+ apt-get update
Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)

+ apt-get install zip -y
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
```

Can you tell me how can we resolve these permission issues?

**Comment by everflux** [comment]
The default user which is used to execute commands is a non-root user. The reason is to support using the image to create a project without getting files owned by root and to allow easy usage with OpenShift based environments.
To solve your issue there are basically three options: You can either create your own docker image which installs the desired packages, you can run the container as root to get the permissions to install packages or you run your tasks in a different container or even outside docker.

Since the requirement to use zip might be quite common I added the zip package dependency and you can use it with the next build ( :latest is just being built, 8.3.6 probably next week)

Thanks for opening the issue, I hope the answer and updated image solves your requirements.
